# Generated by Django 5.1.6 on 2025-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_alter_address_email_alter_address_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('order_no', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('order_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
